// Generated by CoffeeScript 2.4.1
(function() {
  /*
   * @author Jinzulen
   * @license Apache 2.0
   * @copyright Copyright 2020 Khalil G. <https://github.com/Jinzulen>
   */
  var EmojiCache, FS, JSONConfig, JSONDB, Path;

  FS = require("fs");

  Path = require("path");

  JSONDB = require("node-json-db");

  JSONConfig = require("node-json-db/dist/lib/JsonDBConfig");

  module.exports = new (EmojiCache = class EmojiCache {
    constructor() {
      this.Storage = new JSONDB.JsonDB(new JSONConfig.Config("./Cache/EmojiGG", true, false));
      this.Storage.push("/Stats");
      this.Storage.push("/Emoji");
      this.Storage.push("/Packs");
      this.Storage.push("/Categories");
    }

    getCache(Stores) {
      var Data, E;
      try {
        Data = this.Storage.getData("/")[`${Stores.replace("/", "")}`];
        if (typeof Data !== "undefined") {
          return Data;
        } else {
          return false;
        }
      } catch (error) {
        E = error;
        throw E;
      }
    }

    setCache(Stores, Data) {
      var E;
      try {
        return this.Storage.push(Stores, Data);
      } catch (error) {
        E = error;
        throw E;
      }
    }

  });

}).call(this);
