// Generated by CoffeeScript 2.4.1
(function() {
  /*
   * @author Jinzulen
   * @license Apache 2.0
   * @copyright Copyright 2020 Khalil G. <https://github.com/Jinzulen>
   */
  var API, GrabStatistics;

  API = require("../../API/EmojiAPI");

  module.exports = GrabStatistics = class GrabStatistics {
    constructor(Options, Callback) {
      return new Promise(function(Resolve, Reject) {
        return API.contactAPI("https://discordemoji.com/api/?request=stats", function(Error, Data) {
          var Store, i, len, o, results;
          if (Error) {
            Reject(Error);
          }
          if (Options.length >= 1) {
            Store = {};
            results = [];
            for (i = 0, len = Options.length; i < len; i++) {
              o = Options[i];
              Store[o] = Data[o];
              results.push(Resolve(Store));
            }
            return results;
          } else {
            return Resolve(Data);
          }
        });
      });
    }

  };

}).call(this);
