// Generated by CoffeeScript 2.4.1
(function() {
  /*
   * @author Jinzulen
   * @license Apache 2.0
   * @copyright Copyright 2020 Khalil G. <https://github.com/Jinzulen>
   */
  var API, Methods;

  // Grab categories just once at run-time.
  API = require("./API/EmojiAPI");

  API.GrabCategories();

  // Method routes scaffolding.
  Methods = {};

  Methods.Packs = function(ID = null, Callback) {
    return new (require("./Methods/Packs/Search"))(ID, Callback);
  };

  Methods.allEmoji = function(GIF = false, Callback) {
    return new (require("./Methods/Emotes/All"))(GIF, Callback);
  };

  Methods.randomEmoji = function(Input = null, Callback) {
    return new (require("./Methods/Emotes/Random"))(Input, Callback);
  };

  Methods.emojiByID = function(ID, Callback) {
    return new (require("./Methods/Emotes/ID"))(ID, Callback);
  };

  Methods.emojiByName = function(Title, Callback) {
    return new (require("./Methods/Emotes/Title"))(Title, Callback);
  };

  Methods.emojiBySlug = function(Slug, Callback) {
    return new (require("./Methods/Emotes/Slug"))(Slug, Callback);
  };

  Methods.emojiByAuthor = function(Name, GIF = false, Callback) {
    return new (require("./Methods/Emotes/Author"))(Name, GIF, Callback);
  };

  Methods.emojiByLicense = function(License, GIF = false, Callback) {
    return new (require("./Methods/Emotes/License"))(License, GIF, Callback);
  };

  Methods.emojiByCategory = function(Category, Callback) {
    return new (require("./Methods/Emotes/Category"))(Category, Callback);
  };

  Methods.Statistics = function(Options = [], Callback) {
    return new (require("./Methods/Website/Statistics"))(Options, Callback);
  };

  // Return methods.
  module.exports = Methods;

}).call(this);
