// Generated by CoffeeScript 2.4.1
(function() {
  /*
   * @author Jinzulen
   * @license Apache 2.0
   * @copyright Copyright 2020 Khalil G. <https://github.com/Jinzulen>
   */
  var API, GrabEverything;

  API = require("../../API/EmojiAPI");

  module.exports = GrabEverything = class GrabEverything {
    constructor(GIF, Callback) {
      return new Promise(function(Resolve, Reject) {
        return API.contactAPI("https://emoji.gg/api/", function(Error, Data) {
          var Store, e, i, len, results;
          if (Error) {
            Reject(Error);
          }
          if (GIF) {
            Store = [];
            results = [];
            for (i = 0, len = Data.length; i < len; i++) {
              e = Data[i];
              if (e["image"].includes(".gif")) {
                Store.push(e);
                results.push(Resolve(Store));
              } else {
                results.push(void 0);
              }
            }
            return results;
          } else {
            return Resolve(Data);
          }
        });
      });
    }

  };

}).call(this);
