// Generated by CoffeeScript 2.4.1
(function() {
  /*
   * @author Jinzulen
   * @license Apache 2.0
   * @copyright Copyright 2020 Khalil G. <https://github.com/Jinzulen>
   */
  var API, GrabAuthor;

  API = require("../../API/EmojiAPI");

  module.exports = GrabAuthor = class GrabAuthor {
    constructor(Author, GIF, Callback) {
      return new Promise(function(Resolve, Reject) {
        if (!Author) {
          Reject("# [DEmojiJS] Please enter an emote uplaoder to continue.");
        }
        if (typeof Author !== "string") {
          Reject("# [DEmojiJS] Emote author has to be a string.");
        }
        return API.contactAPI("https://emoji.gg/api/", function(Error, Data) {
          var Store, Type, e, i, len, results;
          if (Error) {
            Reject(Error);
          }
          Store = [];
          if (GIF) {
            Type = ".gif";
          } else {
            Type = ".";
          }
          results = [];
          for (i = 0, len = Data.length; i < len; i++) {
            e = Data[i];
            e["submitted_by"] = e["submitted_by"].toLowerCase();
            if (e["submitted_by"] === Author.toLowerCase() && e["image"].includes(Type)) {
              Store.push(e);
              results.push(Resolve(Store));
            } else {
              results.push(void 0);
            }
          }
          return results;
        });
      });
    }

  };

}).call(this);
