// Generated by CoffeeScript 2.4.1
(function() {
  /*
   * @author Jinzulen
   * @license Apache 2.0
   * @copyright Copyright 2020 Khalil G. <https://github.com/Jinzulen>
   */
  var API, GrabCategory;

  API = require("../../API/EmojiAPI");

  module.exports = GrabCategory = class GrabCategory {
    constructor(Category, Callback) {
      return new Promise(function(Resolve, Reject) {
        var Cats, Store;
        if (!Category) {
          Reject("# [DEmojiJS] Please enter an emote category to continue.");
        }
        if (typeof Category !== "string") {
          Reject("# [DEmojiJS] Emote Category has to be a string.");
        }
        // Stores.
        Cats = {};
        Store = [];
        // Grab emotes.
        return API.contactAPI("https://emoji.gg/api/", function(Error, Emotes) {
          if (Error) {
            Reject(Error);
          }
          // Grab categories.
          return API.contactAPI("https://emoji.gg/api/?request=categories", function(Error, Categories) {
            var c, e, i, j, len, len1, ref, results;
            if (Error) {
              Reject(Error);
            }
            ref = Object.keys(Categories);
            // Store all categories in lowercase.
            for (i = 0, len = ref.length; i < len; i++) {
              c = ref[i];
              Cats[c] = Categories[c].toLowerCase();
            }
// Search for emotes that fit the requested category.
            results = [];
            for (j = 0, len1 = Emotes.length; j < len1; j++) {
              e = Emotes[j];
              if (Cats[e["category"]] === Category.toLowerCase()) {
                Store.push(e);
              }
              results.push(Resolve(Store));
            }
            return results;
          });
        });
      });
    }

  };

}).call(this);
