4// Generated by CoffeeScript 2.4.1
(function() {
  /*
   * @author Jinzulen
   * @license Apache 2.0
   * @copyright Copyright 2020 Khalil G. <https://github.com/Jinzulen>
   */
  var API, GrabID;

  API = require("../../API/EmojiAPI");

  module.exports = GrabID = class GrabID {
    constructor(ID, Callback) {
      return new Promise(function(Resolve, Reject) {
        if (!ID) {
          Reject("# [DEmojiJS] Please enter an emote ID to continue.");
        }
        if (typeof ID !== "number") {
          Reject("# [DEmojiJS] Emote ID has to be a number.");
        }
        return API.contactAPI("https://emoji.gg/api/", function(Error, Data) {
          var i, results;
          if (Error) {
            Reject(Error);
          }
          i = 0;
          results = [];
          while (i < Object.keys(Data).length) {
            if (Data[i]["id"] === ID) {
              Resolve(Data[i]);
            }
            results.push(i++);
          }
          return results;
        });
      });
    }

  };

}).call(this);
