// Generated by CoffeeScript 2.4.1
(function() {
  /*
   * @author Jinzulen
   * @license Apache 2.0
   * @copyright Copyright 2020 Khalil G. <https://github.com/Jinzulen>
   */
  var API, GrabLicense;

  API = require("../../API/EmojiAPI");

  module.exports = GrabLicense = class GrabLicense {
    constructor(License, GIF, Callback) {
      return new Promise(function(Resolve, Reject) {
        if (!License) {
          Reject("# [DEmojiJS] Please enter a license name to continue.");
        }
        if (typeof License !== "string") {
          Reject("# [DEmojiJS] Emote license has to be a string.");
        }
        return API.contactAPI("https://emoji.gg/api/", function(Error, Data) {
          var Licenses, Store, Type, e, i, len, results;
          if (Error) {
            Reject(Error);
          }
          Store = [];
          License = License.toLowerCase();
          Licenses = {
            "basic": "0",
            "cc by 4.0": "1",
            "wtfpl": "2"
          };
          if (GIF) {
            Type = ".gif";
          } else {
            Type = ".";
          }
          if (!Licenses[License]) {
            Reject(`# [DEmojiJS] ${License} is not a valid license.`);
          }
          results = [];
          for (i = 0, len = Data.length; i < len; i++) {
            e = Data[i];
            if (e["license"] === Licenses[License] && e["image"].includes(Type)) {
              Store.push(e);
              results.push(Resolve(Store));
            } else {
              results.push(void 0);
            }
          }
          return results;
        });
      });
    }

  };

}).call(this);
