// Generated by CoffeeScript 2.4.1
(function() {
  /*
   * @author Jinzulen
   * @license Apache 2.0
   * @copyright Copyright 2020 Khalil G. <https://github.com/Jinzulen>
   */
  var API, GrabRandom;

  API = require("../../API/EmojiAPI");

  module.exports = GrabRandom = class GrabRandom {
    constructor(Input, Callback) {
      return new Promise(function(Resolve, Reject) {
        return API.contactAPI("https://emoji.gg/api/", function(Error, Data) {
          var Cats, Store, e, i, len;
          if (Error) {
            Reject(Error);
          }
          if (Input) {
            Cats = [];
            Store = [];
            for (i = 0, len = Data.length; i < len; i++) {
              e = Data[i];
              if (typeof Input !== "boolean") {
                API.contactAPI("https://emoji.gg/api/?request=categories", function(Error, Categories) {
                  var c, j, len1, ref, results;
                  if (Error) {
                    throw Error;
                  }
                  ref = Object.keys(Categories);
                  // Store all categories in lowercase.
                  results = [];
                  for (j = 0, len1 = ref.length; j < len1; j++) {
                    c = ref[j];
                    results.push(Cats[c] = Categories[c].toLowerCase());
                  }
                  return results;
                });
                if (Cats[e["category"]] === Input.toLowerCase()) {
                  Store.push(e);
                }
              }
              if (typeof Input === "boolean" && Input !== false) {
                if (e["image"].includes(".gif")) {
                  Store.push(e);
                }
              }
            }
            return Resolve(Store[Math.floor(Math.random() * Store.length + 1)]);
          } else {
            return Resolve(Data[Math.floor(Math.random() * Object.keys(Data).length + 1)]);
          }
        });
      });
    }

  };

}).call(this);
