// Generated by CoffeeScript 2.4.1
(function() {
  /*
   * @author Jinzulen
   * @license Apache 2.0
   * @copyright Copyright 2020 Khalil G. <https://github.com/Jinzulen>
   */
  var API, GrabSlug;

  API = require("../../API/EmojiAPI");

  module.exports = GrabSlug = class GrabSlug {
    constructor(Slug, Callback) {
      return new Promise(function(Resolve, Reject) {
        if (!Slug) {
          Reject("# [DEmojiJS] Please enter an emote slug to continue.");
        }
        if (typeof Slug !== "string") {
          Reject("# [DEmojiJS] Emote slug has to be a string.");
        }
        return API.contactAPI("https://emoji.gg/api/", function(Error, Data) {
          var i, results;
          if (Error) {
            Reject(Error);
          }
          i = 0;
          results = [];
          while (i < Object.keys(Data).length) {
            if (Data[i]["slug"] === Slug) {
              Resolve(Data[i]);
            }
            results.push(i++);
          }
          return results;
        });
      });
    }

  };

}).call(this);
