// Generated by CoffeeScript 2.4.1
(function() {
  /*
   * @author Jinzulen
   * @license Apache 2.0
   * @copyright Copyright 2020 Khalil G. <https://github.com/Jinzulen>
   */
  var API, SearchPacks;

  API = require("../../API/EmojiAPI");

  module.exports = SearchPacks = class SearchPacks {
    constructor(ID, Callback) {
      return new Promise(function(Resolve, Reject) {
        return API.contactAPI("https://discordemoji.com/api/packs", function(Error, Packs) {
          var Store, i, len, p, results;
          if (Error) {
            Reject(Error);
          }
          if (ID) {
            Store = {};
            results = [];
            for (i = 0, len = Packs.length; i < len; i++) {
              p = Packs[i];
              // Get rid of case sensitivity.
              if (typeof ID !== "number") {
                ID = ID.toLowerCase();
              }
              Store["id"] = p["id"];
              Store["slug"] = p["slug"];
              Store["image"] = p["image"];
              Store["amount"] = p["amount"];
              Store["download"] = p["download"];
              Store["name"] = p["name"].toLowerCase();
              // Return results.
              if (Store["id"] === ID || Store["name"] === ID || Store["slug"] === ID) {
                results.push(Resolve(p));
              } else {
                results.push(void 0);
              }
            }
            return results;
          } else {
            return Resolve(Packs);
          }
        });
      });
    }

  };

}).call(this);
